package org.dromara.creator.client;

import lombok.Data;

import java.math.BigDecimal;
import java.util.Date;

/**
 * API call log generated by one TikHub client session.
 */
@Data
public class TikHubCallLogDraft {

    private String endpoint;
    private String requestMethod;
    private String requestKey;
    private Integer httpStatus;
    private String providerCode;
    private Boolean success;
    private Integer latencyMs;
    private BigDecimal unitPriceUsd;
    private BigDecimal unitPriceCny;
    private BigDecimal estimatedCostCny;
    private String errorMessage;
    private Date calledAt;
}
