#!/usr/bin/env bash
set -euo pipefail

# Generate a production deploy/.env.prod file on Linux servers.
#
# Usage:
#   bash scripts/gen-prod-secrets.sh your-domain.com
#   bash scripts/gen-prod-secrets.sh https://your-domain.com
#
# Output:
#   deploy/.env.prod
#
# This script never commits secrets. deploy/.env.prod is ignored by git.

cd "$(dirname "$0")/.."

DOMAIN="${1:-}"
OUT="deploy/.env.prod"

if [[ -z "$DOMAIN" ]]; then
  echo "Usage: bash scripts/gen-prod-secrets.sh your-domain.com" >&2
  exit 1
fi

if ! command -v openssl >/dev/null 2>&1; then
  echo "openssl is required. Install it first." >&2
  exit 1
fi

if [[ "$DOMAIN" != http://* && "$DOMAIN" != https://* ]]; then
  DOMAIN="https://${DOMAIN}"
fi
DOMAIN="${DOMAIN%/}"

if [[ "$DOMAIN" != https://* ]]; then
  echo "Domain must use HTTPS: $DOMAIN" >&2
  exit 1
fi

rand_alnum() {
  openssl rand -base64 64 | tr -dc 'A-Za-z0-9' | head -c "${1:-32}"
}

rand_hex() {
  openssl rand -hex "${1:-24}"
}

tmp_dir="$(mktemp -d)"
trap 'rm -rf "$tmp_dir"' EXIT

openssl genrsa -out "$tmp_dir/request-private.pem" 2048 >/dev/null 2>&1
openssl pkcs8 -topk8 -inform PEM -in "$tmp_dir/request-private.pem" -outform PEM -nocrypt -out "$tmp_dir/request-private-pkcs8.pem" >/dev/null 2>&1
openssl rsa -in "$tmp_dir/request-private.pem" -pubout -out "$tmp_dir/request-public.pem" >/dev/null 2>&1

API_PRIVATE_KEY="$(grep -v -- '-----' "$tmp_dir/request-private-pkcs8.pem" | tr -d '\r\n')"
WEB_PUBLIC_KEY="$(grep -v -- '-----' "$tmp_dir/request-public.pem" | tr -d '\r\n')"

mkdir -p deploy

cat > "$OUT" <<EOF
# Generated by scripts/gen-prod-secrets.sh
# Do not commit this file.

CONTAINER_PREFIX=tiktok-platform

# ---------- MySQL, docker internal only ----------
MYSQL_DATABASE=ry-vue
MYSQL_ROOT_PASSWORD=$(rand_alnum 32)
MYSQL_USERNAME=ruoyi
MYSQL_PASSWORD=$(rand_alnum 32)

# ---------- Redis, docker internal only ----------
REDIS_PASSWORD=$(rand_alnum 32)

# ---------- MinIO, docker internal only ----------
MINIO_ROOT_USER=minioadmin
MINIO_ROOT_PASSWORD=$(rand_alnum 32)

# ---------- SnailJob ----------
SNAIL_JOB_TOKEN=$(rand_hex 24)

# ---------- Backend secrets ----------
SA_TOKEN_JWT_SECRET=$(rand_alnum 64)
API_DECRYPT_REQUEST_PRIVATE_KEY=${API_PRIVATE_KEY}
API_DECRYPT_RESPONSE_PUBLIC_KEY=${WEB_PUBLIC_KEY}

# ---------- Web build args ----------
WEB_APP_TITLE=Creator Monitoring
WEB_APP_LOGO_TITLE=Creator Monitoring
WEB_CONTEXT_PATH=/
WEB_MONITOR_ADMIN=/admin/applications
WEB_SNAILJOB_ADMIN=/snail-job
WEB_BASE_API=/prod-api
WEB_BUILD_COMPRESS=gzip
WEB_RSA_PUBLIC_KEY=${WEB_PUBLIC_KEY}
WEB_CLIENT_ID=e5cd7e4891bf95d1d19206ce24a7b32e
WEB_WEBSOCKET=false
WEB_SSE=true

# ---------- CORS ----------
CORS_ALLOWED_ORIGINS=${DOMAIN}

# ---------- TikHub ----------
TIKHUB_ENABLED=true
TIKHUB_API_TOKEN=

# ---------- WeChat Mini Program ----------
WECHAT_MINIAPP_APPID=wxa046df0d75f9a06c
WECHAT_MINIAPP_APP_SECRET=REPLACE_WITH_WECHAT_APP_SECRET
WECHAT_MINIAPP_MOCK_ENABLED=false

# ---------- Public web ports ----------
WEB_HTTP_PORT=80
WEB_HTTPS_PORT=443

# ---------- JVM ----------
JAVA_OPTS=-Xms512m -Xmx1024m
EOF

chmod 600 "$OUT"

echo "Generated $OUT"
echo ""
echo "Before starting Docker, edit this value:"
echo "  WECHAT_MINIAPP_APP_SECRET"
echo ""
echo "Then validate:"
echo "  docker compose --env-file deploy/.env.prod -f deploy/docker-compose.prod.yml config --quiet"
