SET NAMES utf8mb4;

-- Real SnailJob schedule for creator monitoring collection.
-- The unique key (namespace_id, biz_id) makes this script idempotent.

INSERT INTO sj_job (
    namespace_id,
    biz_id,
    group_name,
    job_name,
    args_str,
    args_type,
    next_trigger_at,
    job_status,
    task_type,
    route_key,
    executor_type,
    executor_info,
    trigger_type,
    trigger_interval,
    block_strategy,
    executor_timeout,
    max_retry_times,
    parallel_num,
    retry_interval,
    bucket_index,
    resident,
    notify_ids,
    owner_id,
    labels,
    description,
    ext_attrs,
    deleted,
    create_dt,
    update_dt
) VALUES (
    'prod',
    'creator-monitor-collect',
    'ruoyi_group',
    'Creator monitor collection',
    NULL,
    1,
    UNIX_TIMESTAMP(CURRENT_TIMESTAMP(3)) * 1000 + 60000,
    1,
    1,
    4,
    1,
    'creatorMonitorCollectJob',
    2,
    '60',
    1,
    300,
    3,
    1,
    30,
    0,
    0,
    '',
    NULL,
    '',
    'Collect due creator and content monitoring targets every 60 seconds.',
    '',
    0,
    NOW(),
    NOW()
)
ON DUPLICATE KEY UPDATE
    group_name = VALUES(group_name),
    job_name = VALUES(job_name),
    job_status = VALUES(job_status),
    route_key = VALUES(route_key),
    executor_type = VALUES(executor_type),
    executor_info = VALUES(executor_info),
    trigger_type = VALUES(trigger_type),
    trigger_interval = VALUES(trigger_interval),
    block_strategy = VALUES(block_strategy),
    executor_timeout = VALUES(executor_timeout),
    max_retry_times = VALUES(max_retry_times),
    parallel_num = VALUES(parallel_num),
    retry_interval = VALUES(retry_interval),
    description = VALUES(description),
    deleted = 0,
    update_dt = NOW();
