SET NAMES utf8mb4;

-- --------------------------------------------------------
-- Creator Monitor phase 1 schema
-- Platform: douyin first, xiaohongshu reserved by platform field
-- ID strategy: RuoYi ASSIGN_ID/Snowflake generated by backend
-- --------------------------------------------------------

-- ----------------------------
-- Platform creator account
-- ----------------------------
drop table if exists cm_creator_account;
create table cm_creator_account
(
    creator_id              bigint(20)      not null                    comment 'creator primary id',
    tenant_id               varchar(20)     default '000000'            comment 'tenant id',
    platform                varchar(32)     not null                    comment 'platform: douyin,xiaohongshu',
    platform_creator_id     varchar(128)    not null                    comment 'platform stable creator id, douyin sec_user_id preferred',
    platform_user_id        varchar(128)    default null                comment 'platform numeric uid if available',
    platform_display_id     varchar(128)    default null                comment 'public display id, such as douyin number',
    nickname                varchar(128)    not null                    comment 'creator nickname',
    avatar_url              varchar(1000)   default null                comment 'avatar url',
    signature               varchar(2000)   default null                comment 'bio/signature',
    homepage_url            varchar(1000)   default null                comment 'creator homepage url',
    ip_location             varchar(128)    default null                comment 'public ip location',
    gender                  varchar(32)     default null                comment 'gender if available',
    follower_count          bigint(20)      default 0                   comment 'latest follower count',
    following_count         bigint(20)      default 0                   comment 'latest following count',
    total_favorited_count   bigint(20)      default 0                   comment 'latest total liked count',
    content_count           int(11)         default 0                   comment 'latest published content count',
    profile_status          varchar(32)     default 'pending'           comment 'pending,full,partial,failed',
    last_profile_collect_at datetime        default null                comment 'last profile collection time',
    last_content_scan_at    datetime        default null                comment 'last new content scan time',
    raw_profile_json        json            default null                comment 'latest raw profile payload',
    create_dept             bigint(20)      default null                comment 'create department',
    create_by               bigint(20)      default null                comment 'create user',
    create_time             datetime        default null                comment 'create time',
    update_by               bigint(20)      default null                comment 'update user',
    update_time             datetime        default null                comment 'update time',
    del_flag                char(1)         default '0'                 comment 'delete flag: 0 active, 1 deleted',
    primary key (creator_id),
    unique key uk_cm_creator_platform_id (tenant_id, platform, platform_creator_id),
    key idx_cm_creator_display_id (tenant_id, platform, platform_display_id),
    key idx_cm_creator_owner (tenant_id, create_by, create_dept),
    key idx_cm_creator_collect_at (last_profile_collect_at)
) engine=innodb comment='creator monitor - platform creator account';

-- ----------------------------
-- Platform content/post
-- ----------------------------
drop table if exists cm_content_post;
create table cm_content_post
(
    content_id              bigint(20)      not null                    comment 'content primary id',
    tenant_id               varchar(20)     default '000000'            comment 'tenant id',
    platform                varchar(32)     not null                    comment 'platform: douyin,xiaohongshu',
    creator_id              bigint(20)      default null                comment 'creator id, nullable before creator is recognized',
    platform_content_id     varchar(128)    not null                    comment 'platform stable content id, douyin aweme_id preferred',
    content_type            varchar(32)     default 'video'             comment 'video,image,text,mix',
    title                   varchar(512)    default null                comment 'short title',
    description             text                                      comment 'full caption/copywriting',
    cover_url               varchar(1000)   default null                comment 'cover url',
    content_url             varchar(1000)   default null                comment 'canonical content url',
    share_url               varchar(1000)   default null                comment 'original share url',
    publish_time            datetime        default null                comment 'platform publish time',
    first_seen_at           datetime        default null                comment 'first detected by system',
    added_source            varchar(32)     default 'manual_link'       comment 'manual_link,creator_discovery,task_submission,migration',
    latest_like_count       bigint(20)      default null                comment 'latest like count',
    latest_comment_count    bigint(20)      default null                comment 'latest comment count',
    latest_collect_count    bigint(20)      default null                comment 'latest collect/favorite count',
    latest_share_count      bigint(20)      default null                comment 'latest share count',
    latest_play_count       bigint(20)      default null                comment 'latest play count, reserved',
    metrics_status          varchar(32)     default 'pending'           comment 'pending,full,partial,failed',
    last_metrics_collect_at datetime        default null                comment 'last metrics collection time',
    raw_content_json        json            default null                comment 'latest raw content payload',
    create_dept             bigint(20)      default null                comment 'create department',
    create_by               bigint(20)      default null                comment 'create user',
    create_time             datetime        default null                comment 'create time',
    update_by               bigint(20)      default null                comment 'update user',
    update_time             datetime        default null                comment 'update time',
    del_flag                char(1)         default '0'                 comment 'delete flag: 0 active, 1 deleted',
    primary key (content_id),
    unique key uk_cm_content_platform_id (tenant_id, platform, platform_content_id),
    key idx_cm_content_creator_publish (creator_id, publish_time),
    key idx_cm_content_latest_collect (tenant_id, last_metrics_collect_at),
    key idx_cm_content_create_by (tenant_id, create_by, create_dept),
    fulltext key ft_cm_content_text (title, description)
) engine=innodb comment='creator monitor - platform content post';

-- ----------------------------
-- Monitor target
-- One business target can be creator_collection or single_content.
-- ----------------------------
drop table if exists cm_monitor_target;
create table cm_monitor_target
(
    target_id                       bigint(20)      not null                    comment 'monitor target primary id',
    tenant_id                       varchar(20)     default '000000'            comment 'tenant id',
    target_type                     varchar(32)     not null                    comment 'creator_collection,single_content',
    platform                        varchar(32)     not null                    comment 'platform: douyin,xiaohongshu',
    target_name                     varchar(128)    not null                    comment 'display name',
    owner_user_id                   bigint(20)      not null                    comment 'business owner user id',
    owner_dept_id                   bigint(20)      default null                comment 'business owner department id',
    direct_superior_user_id         bigint(20)      default null                comment 'owner direct superior snapshot',
    creator_id                      bigint(20)      default null                comment 'creator target points to creator account',
    content_id                      bigint(20)      default null                comment 'single content target points to content post',
    baseline_time                   datetime        default null                comment 'creator monitor only discovers content published after this time',
    discover_new_content            tinyint(1)      default 0                   comment 'whether to discover new content from creator homepage',
    profile_collect_interval_min    int(11)         default 360                 comment 'creator profile collection interval minutes',
    content_collect_interval_min    int(11)         default 30                  comment 'content metrics collection interval minutes',
    last_profile_collect_at         datetime        default null                comment 'last profile collection time for this target',
    last_content_collect_at         datetime        default null                comment 'last content metrics collection time for this target',
    last_discovery_at               datetime        default null                comment 'last new content discovery time',
    next_profile_collect_at         datetime        default null                comment 'next profile collection time',
    next_content_collect_at         datetime        default null                comment 'next content metrics collection time',
    next_discovery_at               datetime        default null                comment 'next discovery time',
    status                          varchar(32)     default 'active'            comment 'active,paused,stopped,failed',
    data_status                     varchar(32)     default 'pending'           comment 'pending,full,partial,no_new_content,failed,budget_limited',
    remark                          varchar(500)    default null                comment 'business remark',
    tags                            varchar(500)    default null                comment 'comma separated tags',
    create_dept                     bigint(20)      default null                comment 'create department',
    create_by                       bigint(20)      default null                comment 'create user',
    create_time                     datetime        default null                comment 'create time',
    update_by                       bigint(20)      default null                comment 'update user',
    update_time                     datetime        default null                comment 'update time',
    del_flag                        char(1)         default '0'                 comment 'delete flag: 0 active, 1 deleted',
    primary key (target_id),
    key idx_cm_target_owner (tenant_id, owner_user_id, owner_dept_id),
    key idx_cm_target_creator (tenant_id, creator_id),
    key idx_cm_target_content (tenant_id, content_id),
    key idx_cm_target_schedule (tenant_id, status, next_content_collect_at),
    key idx_cm_target_type_status (tenant_id, platform, target_type, status)
) engine=innodb comment='creator monitor - monitor target';

-- ----------------------------
-- Target and content relation
-- Allows the same platform content to be monitored by multiple business targets.
-- ----------------------------
drop table if exists cm_monitor_target_content;
create table cm_monitor_target_content
(
    id                   bigint(20)      not null                    comment 'primary id',
    tenant_id            varchar(20)     default '000000'            comment 'tenant id',
    target_id            bigint(20)      not null                    comment 'monitor target id',
    content_id           bigint(20)      not null                    comment 'content id',
    relation_source      varchar(32)     default 'manual_link'       comment 'manual_link,creator_discovery,task_submission',
    published_after_base tinyint(1)      default 1                   comment 'whether content publish time is after target baseline',
    first_bound_at       datetime        default null                comment 'first bound time',
    last_collected_at    datetime        default null                comment 'last metrics collection time through this target',
    status               varchar(32)     default 'active'            comment 'active,paused,removed',
    create_dept          bigint(20)      default null                comment 'create department',
    create_by            bigint(20)      default null                comment 'create user',
    create_time          datetime        default null                comment 'create time',
    update_by            bigint(20)      default null                comment 'update user',
    update_time          datetime        default null                comment 'update time',
    del_flag             char(1)         default '0'                 comment 'delete flag: 0 active, 1 deleted',
    primary key (id),
    unique key uk_cm_target_content (tenant_id, target_id, content_id),
    key idx_cm_tcontent_content (tenant_id, content_id),
    key idx_cm_tcontent_collect (tenant_id, status, last_collected_at)
) engine=innodb comment='creator monitor - target content relation';

-- ----------------------------
-- Creator metrics snapshot
-- ----------------------------
drop table if exists cm_creator_snapshot;
create table cm_creator_snapshot
(
    snapshot_id           bigint(20)      not null                    comment 'snapshot primary id',
    tenant_id             varchar(20)     default '000000'            comment 'tenant id',
    creator_id            bigint(20)      not null                    comment 'creator id',
    target_id             bigint(20)      default null                comment 'related monitor target id',
    collected_at          datetime        not null                    comment 'collection time',
    follower_count        bigint(20)      default null                comment 'follower count',
    following_count       bigint(20)      default null                comment 'following count',
    total_favorited_count bigint(20)      default null                comment 'total liked count',
    content_count         int(11)         default null                comment 'content count',
    profile_status        varchar(32)     default 'full'              comment 'full,partial,failed',
    raw_snapshot_json     json            default null                comment 'raw snapshot payload',
    create_time           datetime        default null                comment 'create time',
    primary key (snapshot_id),
    key idx_cm_creator_snapshot_time (tenant_id, creator_id, collected_at),
    key idx_cm_creator_snapshot_target (tenant_id, target_id, collected_at)
) engine=innodb comment='creator monitor - creator metrics snapshot';

-- ----------------------------
-- Content metrics snapshot
-- ----------------------------
drop table if exists cm_content_snapshot;
create table cm_content_snapshot
(
    snapshot_id             bigint(20)      not null                    comment 'snapshot primary id',
    tenant_id               varchar(20)     default '000000'            comment 'tenant id',
    content_id              bigint(20)      not null                    comment 'content id',
    target_id               bigint(20)      default null                comment 'related monitor target id',
    collected_at            datetime        not null                    comment 'collection time',
    like_count              bigint(20)      default null                comment 'like count',
    comment_count           bigint(20)      default null                comment 'comment count',
    collect_count           bigint(20)      default null                comment 'collect/favorite count',
    share_count             bigint(20)      default null                comment 'share count',
    play_count              bigint(20)      default null                comment 'play count, reserved',
    like_delta              bigint(20)      default null                comment 'like growth from previous snapshot',
    comment_delta           bigint(20)      default null                comment 'comment growth from previous snapshot',
    collect_delta           bigint(20)      default null                comment 'collect growth from previous snapshot',
    share_delta             bigint(20)      default null                comment 'share growth from previous snapshot',
    metrics_status          varchar(32)     default 'full'              comment 'full,partial,failed',
    missing_metric_fields   varchar(500)    default null                comment 'missing fields when partial',
    raw_snapshot_json       json            default null                comment 'raw snapshot payload',
    create_time             datetime        default null                comment 'create time',
    primary key (snapshot_id),
    key idx_cm_content_snapshot_time (tenant_id, content_id, collected_at),
    key idx_cm_content_snapshot_target (tenant_id, target_id, collected_at),
    key idx_cm_content_snapshot_latest (tenant_id, collected_at)
) engine=innodb comment='creator monitor - content metrics snapshot';

-- ----------------------------
-- Collection run log
-- ----------------------------
drop table if exists cm_collection_run;
create table cm_collection_run
(
    run_id              bigint(20)      not null                    comment 'collection run primary id',
    tenant_id           varchar(20)     default '000000'            comment 'tenant id',
    run_type            varchar(64)     not null                    comment 'creator_profile,content_metrics,new_content_discovery,manual_identify',
    trigger_source      varchar(32)     default 'system'            comment 'system,manual,snailjob,api',
    provider            varchar(32)     default 'tikhub'            comment 'api provider',
    platform            varchar(32)     not null                    comment 'platform',
    target_id           bigint(20)      default null                comment 'monitor target id',
    creator_id          bigint(20)      default null                comment 'creator id',
    content_id          bigint(20)      default null                comment 'content id',
    snail_job_id        varchar(128)    default null                comment 'snailjob job id if available',
    status              varchar(32)     default 'running'           comment 'running,success,partial,failed,skipped,budget_limited',
    started_at          datetime        default null                comment 'started time',
    ended_at            datetime        default null                comment 'ended time',
    duration_ms         int(11)         default null                comment 'duration milliseconds',
    discovered_count    int(11)         default 0                   comment 'new content discovered count',
    collected_count     int(11)         default 0                   comment 'successfully collected object count',
    failed_count        int(11)         default 0                   comment 'failed object count',
    api_call_count      int(11)         default 0                   comment 'external api call count',
    estimated_cost_cny  decimal(12,4)   default 0.0000              comment 'estimated api cost cny',
    error_code          varchar(128)    default null                comment 'error code',
    error_message       varchar(2000)   default null                comment 'error message',
    result_summary_json json            default null                comment 'run summary, endpoint list and field mapping',
    create_dept         bigint(20)      default null                comment 'create department',
    create_by           bigint(20)      default null                comment 'create user',
    create_time         datetime        default null                comment 'create time',
    primary key (run_id),
    key idx_cm_run_time (tenant_id, started_at),
    key idx_cm_run_status (tenant_id, status, run_type),
    key idx_cm_run_target (tenant_id, target_id, started_at),
    key idx_cm_run_content (tenant_id, content_id, started_at)
) engine=innodb comment='creator monitor - collection run log';

-- ----------------------------
-- External API call log
-- ----------------------------
drop table if exists cm_api_call_log;
create table cm_api_call_log
(
    call_id             bigint(20)      not null                    comment 'api call primary id',
    tenant_id           varchar(20)     default '000000'            comment 'tenant id',
    run_id              bigint(20)      default null                comment 'collection run id',
    provider            varchar(32)     default 'tikhub'            comment 'api provider',
    platform            varchar(32)     default 'douyin'            comment 'platform',
    endpoint            varchar(255)    not null                    comment 'endpoint path',
    request_method      varchar(16)     default 'GET'               comment 'http method',
    request_key         varchar(255)    default null                comment 'masked request key, such as aweme_id/sec_user_id',
    http_status         int(11)         default null                comment 'http status code',
    provider_code       varchar(64)     default null                comment 'provider response code',
    success             tinyint(1)      default 0                   comment 'whether call succeeded',
    latency_ms          int(11)         default null                comment 'latency milliseconds',
    unit_price_usd      decimal(12,6)   default 0.000000            comment 'provider unit price usd',
    unit_price_cny      decimal(12,6)   default 0.000000            comment 'estimated unit price cny',
    estimated_cost_cny  decimal(12,6)   default 0.000000            comment 'estimated cost cny',
    error_message       varchar(2000)   default null                comment 'error message',
    called_at           datetime        not null                    comment 'called time',
    create_by           bigint(20)      default null                comment 'create user',
    create_time         datetime        default null                comment 'create time',
    primary key (call_id),
    key idx_cm_api_run (tenant_id, run_id),
    key idx_cm_api_time (tenant_id, called_at),
    key idx_cm_api_endpoint (tenant_id, provider, endpoint, called_at)
) engine=innodb comment='creator monitor - external api call log';

-- Alert rules and generated events are installed by creator_alert_migration.sql.
